# Site settings 配置站点
title: 'NGAO DU KÝ - Nhật Ký Ngao Du'
description: 'Blog viết linh tinh về du lịch và những thứ khác'
url: 'http://ngaoduky.com' # your host
permalink:    /:title
# if you don't need baseurl, you should leave this value blank.
baseurl: ''

#Banner 
banner-title: ngaoduky
banner-description: viết linh tinh
# Navigation links
nav:
  Trang chủ: '/'
  Tác giả: '/about.html'
  xuyên việt: /xuyen-viet
  # ứng dụng hay: /ung-dung-hay

# Author
author: 
  name: Xuân Huy
  username: xuanhuy

  
nickname: 'xuanhuyjs'
bio: 'Gã mơ'
# avatar: '/assets/img/profile.png'
avatar: https://graph.facebook.com/100003474639175/picture?width=320&height=320

# Search
search: true

# Night mode
nightMode: false

# Comments
disqus: false
disqus_url: ''


# Keywords of site
keyword: 'Ngao Du Ký, Blog Du Lịch'
# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站url: weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  facebook: 'https://www.facebook.com/ngaoduky.com'
  youtube-play: 'https://www.youtube.com/ngaoduky'
  instagram: 'https://www.instagram.com/ngaoduky'
  twitter: 'https://twitter.com/ngaoduky'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 5
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

RSS: false

# Plugins
gems: [jekyll-paginate]



# Tag config
tags_config:
  -
    slug: nha-trang
    name: Nha Trang
  -
    slug: xuyen-viet
    name: Xuyên Việt
  -
    slug: phu-yen
    name: Phú Yên
  -
    slug: tuy-hoa
    name: Tuy Hòa
  -
    slug: mui-dien
    name: Mũi Điện
  -
    slug: binh-thuan
    name: Bình Thuận
  -
    slug: vinh-hy
    name: Vĩnh Hy
  -
    slug: phan-rang
    name: Phan Rang
  -
    slug: tuy-phong
    name: Tuy Phong
  -
    slug: ta-nang
    name: Tà Năng
  -
    slug: phan-dung
    name: Phan Dũng
  -
    slug: trekking
    name: Trekking
  -
    slug: bich-hoa
    name: Bích Họa
  -
    slug: tam-thanh
    name: Tam Thanh
  -
    slug: quang-nam
    name: Quảng Nam
  -
    slug: kayak
    name: Kayak
  -
    slug: da-nang
    name: Đà Nẵng
  -
    slug: song-han
    name: Sông Hàn
  -
    slug: van-buong
    name: Vạn Buồng
  -
    slug: dak-lak
    name: Đắk Lắk
  -
    slug: bac-trung-bo
    name: Bắc Trung Bộ
  -
    slug: deo-hai-van
    name: Đèo Hải Vân
  -
    slug: hue
    name: Huế
  -
    slug: quang-tri
    name: Quảng Trị
  -
    slug: quang-binh
    name: Quảng Bình
  -
    slug: dong-phong-nha
    name: Động Phong Nha
  -
    slug: suoi-nuoc-mooc
    name: Suối Nước Moọc
  -
    slug: vung-chua
    name: Vũng Chùa
  -
    slug: deo-ngang
    name: Đèo Ngang
  -
    slug: lang-sen
    name: Làng Sen
  -
    slug: bai-mon
    name: Bãi Môn
  -
    slug: bai-xep
    name: Bãi Xép
  -
    slug: ganh-da-dia
    name: Gành Đá Dĩa
  -
    slug: eo-gio
    name: Eo Gió
  -
    slug: quang-ngai
    name: Quảng Ngãi
  -
    slug: quy-nhon
    name: Quy Nhơn
  -
    slug: binh-dinh
    name: Bình Định
  -
    slug: tuy-an
    name: Tuy An
  -
    slug: a-la-carte
    name: A La Carte
  -
    slug: thu-bon
    name: Thu Bồn
  -
    slug: nho-ba-moi
    name: Nho Ba Mọi
  -
    slug: thap-cham
    name: Tháp Chàm
  -
    slug: cong-coffee
    name: Cộng Coffee


  
    
    
# Category config 
category_configs:
  -
    url: kinh-nghiem
    name: Kinh Nghiệm
  -
    url: ngao-du-ky
    name: Ngao du ký     
  -
    url: du-ky
    name: Du Ký
  -
    url: xuyen-viet
    name: Xuyên Việt  
